import { Category, Product } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 1,
    label: 'All',
    image: '/categories/category-avatar.jpg',
  },
  {
    id: 2,
    label: 'Adults',
    image: '/categories/category-avatar.jpg',
  },
  {
    id: 3,
    label: 'Kids',
    image: '/categories/category-avatar.jpg',
  },
  {
    id: 4,
    label: 'Cooling',
    image: '/categories/category-avatar.jpg',
  },
  {
    id: 5,
    label: 'Gift sets',
    image: '/categories/category-avatar.jpg',
  },
];

export const CATEGORY_PRODUCT: Product[] = [
  {
    id: 1,
    slug: 'nord-classic-weighted-blanket',
    image: '/product/bestselller.png',
    title: 'Nord Classic Weighted Blanket',
    price: 249,
    originalPrice: 289,
    badge: 'Best Seller',
    rating: 4.9,
    reviewCount: 1284,
    weight: '7 kg',
    dimensions: '150 × 200 cm',
  },
  {
    id: 2,
    slug: 'nord-premium-weighted-blanket',
    image: '/product/bestselller.png',
    title: 'Nord Premium Weighted Blanket',
    price: 299,
    originalPrice: 349,
    badge: 'Popular',
    rating: 4.8,
    reviewCount: 956,
    weight: '9 kg',
    dimensions: '150 × 200 cm',
  },
  {
    id: 3,
    slug: 'nord-cooling-weighted-blanket',
    image: '/product/bestselller.png',
    title: 'Nord Cooling Weighted Blanket',
    price: 279,
    originalPrice: 329,
    badge: 'New',
    rating: 4.9,
    reviewCount: 742,
    weight: '7 kg',
    dimensions: '140 × 200 cm',
  },
  {
    id: 4,
    slug: 'nord-luxury-weighted-blanket',
    image: '/product/bestselller.png',
    title: 'Nord Luxury Weighted Blanket',
    price: 349,
    originalPrice: 399,
    badge: 'Best Seller',
    rating: 5,
    reviewCount: 1842,
    weight: '12 kg',
    dimensions: '200 × 220 cm',
  },
  {
    id: 5,
    slug: 'nord-kids-weighted-blanket',
    image: '/product/bestselller.png',
    title: 'Nord Kids Weighted Blanket',
    price: 199,
    originalPrice: 229,
    badge: 'Kids',
    rating: 4.8,
    reviewCount: 521,
    weight: '4 kg',
    dimensions: '100 × 150 cm',
  },
  {
    id: 6,
    slug: 'nord-organic-weighted-blanket',
    image: '/product/bestselller.png',
    title: 'Nord Organic Weighted Blanket',
    price: 269,
    originalPrice: 319,
    badge: 'Organic',
    rating: 4.9,
    reviewCount: 897,
    weight: '7 kg',
    dimensions: '150 × 200 cm',
  },
  {
    id: 7,
    slug: 'nord-winter-weighted-blanket',
    image: '/product/bestselller.png',
    title: 'Nord Winter Weighted Blanket',
    price: 289,
    originalPrice: 339,
    badge: 'Winter',
    rating: 4.7,
    reviewCount: 663,
    weight: '9 kg',
    dimensions: '150 × 200 cm',
  },
  {
    id: 8,
    slug: 'nord-signature-weighted-blanket',
    image: '/product/bestselller.png',
    title: 'Nord Signature Weighted Blanket',
    price: 329,
    originalPrice: 379,
    badge: 'Signature',
    rating: 5,
    reviewCount: 2154,
    weight: '12 kg',
    dimensions: '200 × 220 cm',
  },
];

export const COMPARISON_DATA = [
  {
    feature: 'Filling',
    restfull: 'Glass beads, even grid',
    traditional: 'Plastic or glass beads, loose pockets',
  },
  {
    feature: 'Noise level',
    restfull: 'Silent',
    traditional: 'Can rustle when you move',
  },
  {
    feature: 'Washability',
    restfull: 'Machine washable, 60°C',
    traditional: 'Often spot-clean only',
  },
  {
    feature: 'Temperature',
    restfull: 'Breathable, cools as you sleep',
    traditional: 'Can trap body heat',
  },
  {
    feature: 'Certification',
    restfull: 'CE certified, OEKO-TEX® cotton',
    traditional: 'Varies by manufacturer',
  },
];
