import { WishlistItem } from './type';

export const wishlistItems: WishlistItem[] = [
  {
    id: '1',
    name: 'Nord Classic Weighted Blanket',
    badge: 'BEST SELLER',
    image: '/product/bestselller.png',
    rating: 4.9,
    reviewCount: 1284,
    weight: '7 kg',
    dimensions: '150 x 200 cm',
    price: 249,
    originalPrice: 309,
    currency: '€',
  },
  {
    id: '2',
    name: 'Nord Classic Weighted Blanket',
    badge: 'BEST SELLER',
    image: '/product/bestselller.png',
    rating: 4.9,
    reviewCount: 1284,
    weight: '7 kg',
    dimensions: '150 x 200 cm',
    price: 249,
    originalPrice: 309,
    currency: '€',
  },
  {
    id: '3',
    name: 'Nord Classic Weighted Blanket',
    badge: 'BEST SELLER',
    image: '/product/bestselller.png',
    rating: 4.9,
    reviewCount: 1284,
    weight: '7 kg',
    dimensions: '150 x 200 cm',
    price: 249,
    originalPrice: 309,
    currency: '€',
  },
  {
    id: '4',
    name: 'Nord Classic Weighted Blanket',
    badge: 'BEST SELLER',
    image: '/product/bestselller.png',
    rating: 4.9,
    reviewCount: 1284,
    weight: '7 kg',
    dimensions: '150 x 200 cm',
    price: 249,
    originalPrice: 309,
    currency: '€',
  },
  {
    id: '5',
    name: 'Nord Classic Weighted Blanket',
    badge: 'BEST SELLER',
    image: '/product/bestselller.png',
    rating: 4.9,
    reviewCount: 1284,
    weight: '7 kg',
    dimensions: '150 x 200 cm',
    price: 249,
    originalPrice: 309,
    currency: '€',
  },
  {
    id: '6',
    name: 'Nord Classic Weighted Blanket',
    badge: 'BEST SELLER',
    image: '/product/bestselller.png',
    rating: 4.9,
    reviewCount: 1284,
    weight: '7 kg',
    dimensions: '150 x 200 cm',
    price: 249,
    originalPrice: 309,
    currency: '€',
  },
  {
    id: '7',
    name: 'Nord Classic Weighted Blanket',
    badge: 'BEST SELLER',
    image: '/product/bestselller.png',
    rating: 4.9,
    reviewCount: 1284,
    weight: '7 kg',
    dimensions: '150 x 200 cm',
    price: 249,
    originalPrice: 309,
    currency: '€',
  },
  {
    id: '8',
    name: 'Nord Classic Weighted Blanket',
    badge: 'BEST SELLER',
    image: '/product/bestselller.png',
    rating: 4.9,
    reviewCount: 1284,
    weight: '7 kg',
    dimensions: '150 x 200 cm',
    price: 249,
    originalPrice: 309,
    currency: '€',
  },
];

export const sortOptions = [
  { value: 'price-asc', label: 'Price (Low-High)' },
  { value: 'price-desc', label: 'Price (High-Low)' },
  { value: 'rating', label: 'Rating' },
  { value: 'newest', label: 'Newest' },
];
